compiler.h: Undef before redefining __attribute_const__
This is required to avoid warnings like
util/include/linux/compiler.h:8:0: error: "__attribute_const__" redefined [-Werror]

Signed-off-by: Khem Raj <raj.khem@gmail.com>

Upstream-Status: Pending